server:
  port: 9000

logging:
  level:
    org.springframework.security: trace

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pointofdel_user
    username: postgres
    password: postgres

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true

    hibernate:
      ddl-auto: update

app:
  jwt:
    secret: MyJwtSecretABipfapHUWASdbjKALWslkdalKJLWBSDFawiluksdbfawkjuslbfdAWKSBdkawslbudakwjbsdakbwulsdba
    expirationMs: 86400000
